[package]
name = "august-plugin-system"
version = "1.0.0-alpha.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
august-plugin-system-codegen = { path = "codegen", optional = true }
rayon = "1.8.1"
semver = { version = "1.0.21", features = ["serde"] }
serde = { version = "1.0.196", features = ["derive"] }
thiserror = "1.0.56"
walkdir = { version = "2.4.0", optional = true }
zip = { version = "0.6.6", optional = true }

[dev-dependencies]
august-plugin-system-codegen = { path = "codegen" }
semver = { version = "1.0.21", features = ["serde"] }
toml = "0.8.8"
mlua = { version = "0.9.5", features = ["lua54", "vendored", "send"] }

[features]
derive = ["dep:august-plugin-system-codegen"]
archive = ["dep:walkdir", "dep:zip"]
